image: docker:28

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\/release_[a-zA-Z0-9.]+_\d{8}$/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^hotfix\/hotfix_[a-zA-Z0-9.]+_\d{8}$/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^iteration\/iteration_[a-zA-Z0-9.]+_\d{8}$/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^dev$/'
      when: always
    - if : '$CI_COMMIT_BRANCH =~ /^test$/'
      when: always
    - if : '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never


stages:
  - docker-build

# 构建所有模块
build-docker-all:
  stage: docker-build
  when: manual
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}
    # 构建 五子棋 游戏
    - cd  001/gobang_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA}

    - cd   ../../
    # 构建 斗地主 游戏
    - cd  002/doudizhu_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_doudizhu:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_doudizhu:${CI_COMMIT_SHORT_SHA}

    - cd   ../../
    # 构建 uno 游戏
    - cd  003/uno_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_uno:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_uno:${CI_COMMIT_SHORT_SHA}

    - cd   ../../
    # 构建 中国象棋 游戏
    - cd  005/china_chess_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_china_chess:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_china_chess:${CI_COMMIT_SHORT_SHA}

    - cd   ../../
    # 构建 飞行器 游戏
    - cd  006/flychess_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_flychess:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_flychess:${CI_COMMIT_SHORT_SHA}

    - cd   ../../
    # 构建 声音 游戏
    - cd  008/voicejump_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_voicejump:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_voicejump:${CI_COMMIT_SHORT_SHA}

    - cd   ../../
    # 构建 更新游戏
    - cd  game-update
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_update_game:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_update_game:${CI_COMMIT_SHORT_SHA}

  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA} || true
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_doudizhu:${CI_COMMIT_SHORT_SHA} || true
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_uno:${CI_COMMIT_SHORT_SHA} || true
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_china_chess:${CI_COMMIT_SHORT_SHA} || true
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_flychess:${CI_COMMIT_SHORT_SHA} || true
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_voicejump:${CI_COMMIT_SHORT_SHA} || true
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_update_game:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true



# 构建五子棋游戏
build-docker-wzq:
  stage: docker-build
  when: manual
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}
    # 构建 五子棋 游戏
    - cd  001/gobang_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true


# 构建斗地主游戏
build-docker-doudizhu:
  stage: docker-build
  when: manual
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}

    # 构建 斗地主 游戏
    - cd  002/doudizhu_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_doudizhu:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_doudizhu:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_doudizhu:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true

# 构建uno游戏
build-docker-uno:
  stage: docker-build
  when: manual
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}

    # 构建 uno 游戏
    - cd  003/uno_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_uno:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_uno:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_uno:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true

# 构建中国象棋游戏
build-docker_china_chess:
  stage: docker-build
  when: manual
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}

    # 构建 中国象棋 游戏
    - cd  005/china_chess_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_china_chess:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_china_chess:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_china_chess:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true


# 构建飞行棋游戏
build-docker-flychess:
  stage: docker-build
  when: manual
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}

    # 构建 飞行棋 游戏
    - cd  006/flychess_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_flychess:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_flychess:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_flychess:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true

# 构建声音游戏
build-docker-voicejump:
  stage: docker-build
  when: manual
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}

    # 构建 声音 游戏
    - cd  008/voicejump_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_voicejump:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_voicejump:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_voicejump:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true



# 构建声音游戏
build-docker-update_game:
  stage: docker-build
  when: manual
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}

    # 构建 声音 游戏
    - cd  game-update
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_update_game:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_update_game:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_update_game:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true