image: docker:28

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\/release_[a-zA-Z0-9.]+_\d{8}$/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^hotfix\/hotfix_[a-zA-Z0-9.]+_\d{8}$/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^iteration\/iteration_[a-zA-Z0-9.]+_\d{8}$/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^dev$/'
      when: always
    - if : '$CI_COMMIT_BRANCH =~ /^test$/'
      when: always
    - if : '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never


stages:
  - docker-build

# 构建所有模块
build-docker-lian_jin_game-all:
  stage: docker-build
  image: docker:28  # 使用官方 Docker 镜像
  services:
    - name: docker:dind  # 启用 Docker in Docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""  # 禁用TLS
  script:
    - echo "当前CI工作目录:${CI_PROJECT_DIR}"
    - echo "列出项目根目录内容:"
    - ls -la ${CI_PROJECT_DIR}
    # 构建 sunday-gateway 模块
    - cd  001/gobang_server
    - pwd
    - docker build -t ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA} .
    - docker info
    - docker login ${HARBOR_DOCKER_REGISTRY} -u ${HARBOR_REGISTRY_USER} -p ${HARBOR_REGISTRY_PASSWORD}
    - docker push ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker rmi ${HARBOR_DOCKER_REGISTRY}/${HARBOR_LIBRARY_LIANJIN_GAME_NAME}/lianjin_wzq:${CI_COMMIT_SHORT_SHA} || true
  allow_failure: true
  rules:
    - when: on_success


